### ISSUE TITLE
Search by destination link

### ISSUE THREAD

**Issue by mpdatx** [mbland/custom-links#165]
I'd like to able to search for links by the destination link to see what other links people have created that might be similar to mine or point to the same domain.

**Comment by mbland** [comment]
Since the target links are only stored as part of the short link records, I'm thinking there's two ways of doing this:

* Selecting all existing short links and seeing if a target link matches.
* Migrating to a scheme where target links become hash keys mapped to a list of short links.

There may be legitimate reasons for two separate short links pointing to the same target, but it should be able to notify the user or otherwise discover all short links for a given target.

cc: @akashvbabu

**Comment by mbland** [comment]
Closed by #183.
